name: autism_mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  auto_size_text: ^3.0.0
  http: ^0.13.5
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  equatable: ^2.0.5
  flutter_spinkit: ^5.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.10
  audioplayers: ^0.20.1
  syncfusion_flutter_charts: ^21.2.6
  bulleted_list: ^0.0.1+0.1a
  visibility_detector: ^0.4.0+2
  page_transition: ^2.0.9
  dismissible_page: ^1.0.2
  flutter_analog_clock: ^1.0.3
  flutter_gif: ^0.0.4
  flutter_secure_storage: ^8.0.0
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo-background.png"
  adaptive_icon_foreground: "assets/images/logo-foreground.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  dart_code_metrics: ^5.7.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/components/needs-component.jpg
    - assets/images/components/home-tasks-component.jpg
    - assets/images/components/center-tasks-component.jpg
    - assets/images/components/time-matching-component.jpg
    - assets/images/backgrounds/background1.PNG
    - assets/images/backgrounds/background.PNG
    - assets/images/backgrounds/background1-rotate.png
    - assets/images/backgrounds/background-rotate.png
    - assets/images/aamalLogo.png
    - assets/images/tasks/number-ordering-task.jpg
    - assets/images/tasks/statement-composition-task.jpg
    - assets/images/tasks/number-comparing-task.jpg
    - assets/images/tasks/item-matching-task.jpg
    - assets/images/tasks/analog-matching-task.jpg
    - assets/images/tasks/digital-matching-task.jpg
    - assets/images/tasks/ordering-numbers.jpg
    - assets/images/tasks/ordering-words.jpg
    - assets/images/tasks/bigger-smaller.jpg
    - assets/images/tasks/matching-images.jpg
    - assets/images/tasks/time-matching.jpg
    - assets/images/tasks/bravo.jpg
    - assets/images/start/start-1.png
    - assets/images/start/start-2.jpg
    - assets/images/start/start-3.jpg
    - assets/images/start/start-4.jpg
    - assets/images/start/start-5.jpg
    - assets/images/start/start-6.jpg
    - assets/images/start/start-7.jpg
    - assets/images/waiting-time.png
    - assets/sounds/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Mirza
    fonts:
      - asset: assets/fonts/Mirza-Bold.ttf
      - asset: assets/fonts/Mirza-Medium.ttf
      - asset: assets/fonts/Mirza-Regular.ttf
      - asset: assets/fonts/Mirza-SemiBold.ttf
  - family: Marhey
    fonts:
      - asset: assets/fonts/Marhey-Bold.ttf
      - asset: assets/fonts/Marhey-Medium.ttf
      - asset: assets/fonts/Marhey-Regular.ttf
      - asset: assets/fonts/Marhey-SemiBold.ttf
      - asset: assets/fonts/Marhey-Light.ttf
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Black.ttf
      - asset: assets/fonts/Cairo-Bold.ttf
      - asset: assets/fonts/Cairo-ExtraBold.ttf
      - asset: assets/fonts/Cairo-Medium.ttf
      - asset: assets/fonts/Cairo-Regular.ttf
      - asset: assets/fonts/Cairo-SemiBold.ttf
      - asset: assets/fonts/Cairo-Light.ttf
      - asset: assets/fonts/Cairo-ExtraLight.ttf
  - family: Arial
    fonts:
      - asset: assets/fonts/ARIAL.ttf
      - asset: assets/fonts/ARIALBD 1.ttf
      - asset: assets/fonts/ArialCEMTBlack.ttf
      - asset: assets/fonts/ARIALNB.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
